<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Schema;

class CreateTrnServiceOrderTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('trn_service_order', function (Blueprint $table) {
            $table->integer('id', true)->comment('Unique Record Id for system');
            $table->integer('member_id')->index('FK_trn_service_order_mst_members_1')->comment('links to unique record id of mst_members');
            $table->integer('sales_id')->index('FK_trn_service_order_users_2')->comment('links to unique record id of users');
            $table->integer('service_id')->index('FK_trn_service_order_mst_services');
            $table->string('sap_so_id',50)->comment('SO # generated by SAP');
            $table->string('circuit_id',50)->comment('CID #');
            $table->integer('capacity')->comment('service capacity');
            $table->text('notes', 65535)->comment('note');
            $table->timestamps();
            $table->integer('created_by')->unsigned()->index('FK_trn_service_order_users_3');
            $table->integer('updated_by')->unsigned()->index('FK_trn_service_order_users_4');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('trn_service_order');
    }
}
